### Create/Register a user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@test.com",
    "password": "12348765"
}

### Log in as existing user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "john@test.com",
    "password": "12348765"
}

### Log out user
POST http://localhost:3000/auth/logout

### Get All Users
GET http://localhost:3000/users

### Get User by ID
GET http://localhost:3000/users/2

### Create Task
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Sample Title 5",
    "description": "Sample description",
    "userId": 2
}

### Get all tasks with filter (Needs authorizatoin (token))
GET http://localhost:3000/tasks?page=1&status=pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiam9obkB0ZXN0LmNvbSIsImlhdCI6MTc3OTA3NTc3OCwiZXhwIjoxNzc5MTYyMTc4fQ.7Bta2L0Zb0aHkdxI-hyhYiSxApzoOEa5_g7VXt6KYHI

### Get Task by ID
GET http://localhost:3000/tasks/1

### Update Task
PATCH http://localhost:3000/tasks/2
Content-Type: application/json

{
    "status": "done"
}

### Delete a Task
DELETE http://localhost:3000/tasks/999


